### ISSUE TITLE
Ubuntu 14.04 KeePass 2.28 Incompatable

### ISSUE THREAD

**Issue by bencevans** [pfn/keepasshttp#189]
Please could you advice me on how to get a working version?

![screenshot from 2014-12-26 18 41 11](https://cloud.githubusercontent.com/assets/638535/5558857/dca9445c-8d2e-11e4-901b-46ad78b41ed8.png)
![screenshot from 2014-12-26 18 40 19](https://cloud.githubusercontent.com/assets/638535/5558858/dcadb276-8d2e-11e4-841f-556b4db1cf39.png)

Cheers,

Ben

**Comment by egilh** [comment]
I moved both KeePassHTTP.dll and NewtonsoftJson.dll into the plugin folder.
Using only KeePassHTTP.dll caused KeePass top crash. Using both seems to work nicely for me.
Using Mint17, KeePass 2.28, Chromium and latest dll's.

**Comment by jhult** [comment]
@egilh,

Thanks for the comment. Once I copied NewtonsoftJson.dll into the same folder, it started working.

**Comment by joostshao** [comment]
i use 2.28, but i can not input chinese words...
lost some wine compoents ? or mono libs ?

**Comment by victorjabur** [comment]
I also moved both KeePassHTTP.dll and NewtonsoftJson.dll into the plugin folder.
It is working now, but on start this message is showed.

![Image of Message Error](http://s1.postimg.org/3kyvrhoqn/errorkeepass.png)

**Comment by egilh** [comment]
@victorjabur That error states that you already have something listening at port 19455.
You can try to change the port number that KeePass listens to, or try to figure out what else is using the port.

**Comment by arieljlira** [comment]
Hi, I've just had the same warning reported with ubuntu 14.04.1 and Mint 17.1. 
It went away moving  KeePassHttp.plgx to /usr/lib/keepass2/plugins/ . Maybe this issue could be highlighted in docs https://github.com/pfn/keepasshttp/blob/master/README.md#non-windows--manual-windows-installation.

**Comment by victorjabur** [comment]
My file KeePassHttp.plgx was already in this directory, but the error continues.

**Comment by arieljlira** [comment]
This is my keepass directory tree:
...
/usr/lib/keepass2/
-rw-r--r-- 1 root root     252 nov  3  2013 KeePass.config.xml
-rwxr-xr-x 1 root root 2070016 may 26  2014 KeePass.exe
-rw-r--r-- 1 root root     659 feb  3  2014 KeePass.exe.config
/usr/lib/keepass2/plugins/
-rw-r--r-- 1 root root 157117 feb 11 09:44 KeePassHttp.plgx 
...
wihout DLLs
I'm using keepass2 version 2.25 and the latests https://raw.github.com/pfn/keepasshttp/master/KeePassHttp.plgx

**Comment by victorjabur** [comment]
drwxr-xr-x   3 root root    4096 Jan  8 07:00 .
drwxr-xr-x 212 root root   36864 Fev  3 23:19 ..
-rw-r--r--   1 root root     252 Nov  3  2013 KeePass.config.xml
-rwxr-xr-x   1 root root 2087936 Out 18 08:03 KeePass.exe
-rw-r--r--   1 root root     828 Out 18 08:03 KeePass.exe.config
-rw-r--r--   1 root root   61440 Jan  8 06:57 KeePassHttp.dll
-rw-r--r--   1 root root  319488 Jan  8 07:00 Newtonsoft.Json.dll
drwxr-xr-x   3 root root    4096 Out 17 22:21 plugins

**Comment by victorjabur** [comment]
Removed the .dll file and it works.

sudo rm /usr/lib/keepass2/KeePassHttp.dll

Thanks @arieljlira

**Comment by aivus** [comment]
@arieljlira, I have installed plugin in `/usr/lib/keepass2/` and it works fine for me.

**Comment by arieljlira** [comment]
great @victorjabur !
@aivus I've tried moving KeePassHttp.plgx to /usr/lib/keepass2/ this morning and it failed with the same message reported by @bencevans en this issue. A couple of months ago with an ubuntu 14.04.1 I had the same error. 
However, I moved again from /usr/lib/keepass2/plugins/KeePassHttp.plgx to /usr/lib/keepass2/KeePassHttp.plgx and worked OK :S
I removed PluginCache (~/.local/share/KeePass/PluginCache) but it still works ...

**Comment by SilverWingedSeraph** [comment]
For me, it fails with several hundred repetitions of this, even though I have tried everything suggested in this thread:

X11 Error encountered: 
  Error: BadWindow (invalid Window parameter)
  Request:     12 (0)
  Resource ID: 0x5000040
  Serial:      2566
  Hwnd:        Hwnd, Mapped:True ClientWindow:0x5000040, WholeWindow:0x500003F, Zombie=False, Parent:[<null>]
  Control:     System.Windows.Forms.ImplicitHScrollBar, Minimum: 0, Maximum: 530, Value: 0   at System.Environment.get_StackTrace()
   at System.Windows.Forms.XplatUIX11.HandleError(IntPtr display, XErrorEvent ByRef error_event)
   at System.Drawing.GDIPlus.GdipCreateFromXDrawable_linux(IntPtr , IntPtr , IntPtr ByRef )
   at System.Drawing.Graphics.FromXDrawable(IntPtr drawable, IntPtr display)
   at System.Drawing.Graphics.FromHwnd(IntPtr hwnd)
   at System.Windows.Forms.XplatUIX11.GetAutoScaleSize(System.Drawing.Font font)
   at System.Windows.Forms.XplatUI.GetAutoScaleSize(System.Drawing.Font font)
   at System.Windows.Forms.Form.GetAutoScaleSize(System.Drawing.Font font)
   at System.Windows.Forms.Form..ctor()
   at System.Windows.Forms.MessageBox+MessageBoxForm..ctor(IWin32Window owner, System.String text, System.String caption, MessageBoxButtons buttons, MessageBoxIcon icon, Boolean displayHelpButton)
   at System.Windows.Forms.MessageBox+MessageBoxForm..ctor(IWin32Window owner, System.String text, System.String caption, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defaultButton, MessageBoxOptions options, Boolean displayHelpButton)
   at System.Windows.Forms.MessageBox.Show(System.String text, System.String caption, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defaultButton)
   at KeePassLib.Utility.MessageService.SafeShowMessageBox(System.String strText, System.String strTitle, MessageBoxButtons mb, MessageBoxIcon mi, MessageBoxDefaultButton mdb)
   at KeePassLib.Utility.MessageService.ShowFatal(System.Object[] vLines)
   at KeePass.Program.Main(System.String[] args)


Unhandled Exception:
System.ArgumentException: A null reference or invalid value was found [GDI+ status: InvalidParameter]
  at System.Drawing.GDIPlus.CheckStatus (Status status) [0x00000] in <filename unknown>:0 
  at System.Drawing.Graphics.GdipMeasureString (IntPtr graphics, System.String text, System.Drawing.Font font, System.Drawing.RectangleF& layoutRect, IntPtr stringFormat) [0x00000] in <filename unknown>:0 
  at System.Drawing.Graphics.MeasureString (System.String text, System.Drawing.Font font, Int32 width, System.Drawing.StringFormat format) [0x00000] in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Drawing.Graphics:MeasureString (string,System.Drawing.Font,int,System.Drawing.StringFormat)
  at System.Windows.Forms.TextRenderer.MeasureTextInternal (IDeviceContext dc, System.String text, System.Drawing.Font font, Size proposedSize, TextFormatFlags flags, Boolean useMeasureString) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.TextRenderer.MeasureText (System.String text, System.Drawing.Font font) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.ToolStripMenuItem.CalculatePreferredSize (Size constrainingSize) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.ToolStripItem.GetPreferredSize (Size constrainingSize) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.ToolStripDropDownMenu.OnLayout (System.Windows.Forms.LayoutEventArgs e) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.Control.PerformLayout (System.Windows.Forms.Control affectedControl, System.String affectedProperty) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.Control.PerformLayout () [0x00000] in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.Control:PerformLayout ()
  at System.Windows.Forms.ToolStripItem.OnParentChanged (System.Windows.Forms.ToolStrip oldParent, System.Windows.Forms.ToolStrip newParent) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.ToolStripItem.set_Parent (System.Windows.Forms.ToolStrip value) [0x00000] in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.ToolStripItem:set_Parent (System.Windows.Forms.ToolStrip)
  at System.Windows.Forms.ToolStripItemCollection.Remove (System.Windows.Forms.ToolStripItem value) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.ToolStripItem.Dispose (Boolean disposing) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.ToolStripDropDownItem.Dispose (Boolean disposing) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.ToolStripMenuItem.Dispose (Boolean disposing) [0x00000] in <filename unknown>:0 
  at System.ComponentModel.Component.Finalize () [0x00000] in <filename unknown>:0

**Comment by vimalkumarvelayudhan** [comment]
I got the same error message that the plugin is incompatible with the installed version of KeePass. 

Installing ``mono-complete`` solves the issue on Ubuntu 14.04. It looks like the plugin needs additional mono related dependencies installed to work.

**Comment by francesquini** [comment]
I can confirm that as @vimalkvn said, installing mono-complete fixes the issue.

**Comment by synchrone** [comment]
@vimalkvn is right, generally speaking, but a cleaner solution would be: 
````bash
sudo apt-get install libmono-system-xml-linq4.0-cil libmono-system-data-datasetextensions4.0-cil libmono-system-runtime-serialization4.0-cil
````

Note that @SilverWingedSeraph's issue is a different one.
