### ISSUE TITLE
Keepasshttp plugin compilation fails with keepass 2.34

### ISSUE THREAD

**Issue by bennodepenno** [pfn/keepasshttp#293]
Hi,

On my archlinux machine, I'm running into a plugin compile error when launching keepass 2.34. I've started keepass with --debug parameter which shows 
![screenshot from 2016-11-04 11-00-44](https://cloud.githubusercontent.com/assets/5156552/20001917/88ac7b96-a27e-11e6-9439-8a63a0d58aeb.png)

My mono version: Mono JIT compiler version 4.6.1 (Stable 4.6.1.3/abb06f1 Mon Oct  3 07:51:42 UTC 2016)
My kernel: Linux winecup 4.7.6-1-ARCH #1 SMP PREEMPT Fri Sep 30 19:28:42 CEST 2016 x86_64 GNU/Linux

I've tried the clear cache option in keepass, removing ~/.local/share/KeePass/PluginCache/* and I've verified that the files KeePassHttp.dll and Newtonsoft.Json.dll on my system are exactly the same as in github's mono directory.

Any help would be appreciated in solving this problem. Thank you in advance.

Regards,

Ben

**Comment by Suvidu** [comment]
I have the same problem with Windows (10).  After copying the file into the appropriate folder, KeePass tells me after starting that this plugin is incompatible with this version of KeePass.

**Comment by craigchandler** [comment]
Here is the windows 10 dialog

[Window Title]
KeePass

[Content]
The following plugin is incompatible with the current KeePass version:
C:\Users\Me\AppData\Local\KeePass\PluginCache\Dd4geUqZK9CXILcfL28z\KeePassHttp.dll

Have a look at the plugin's website for an appropriate version.

[Expanded Information]
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
System
   at System.Net.UnsafeNclNativeMethods.SetFileCompletionNotificationModes(CriticalHandle handle, FileCompletionNotificationModes modes)
   at System.Net.HttpListener.CreateRequestQueueHandle()
   at System.Net.HttpListener.Start()
   at KeePassHttp.KeePassHttpExt.Initialize(IPluginHost host)
   at KeePass.Plugins.PluginManager.LoadPlugins(List`1 lFiles, String strTypeName, String strDisplayFilePath, Boolean bSkipCacheFiles)
Boolean SetFileCompletionNotificationModes(System.Runtime.InteropServices.CriticalHandle, FileCompletionNotificationModes)

[^] Details  [OK]

**Comment by pfn** [comment]
This should hopefully resolve itself when I get around to merging #289

**Comment by craigchandler** [comment]
Thanks for the heads up, I can confirm the linked fork is working for me here on windows 10

**Comment by penascimento** [comment]
Hurray!!! this fork is working for my windows 10 also!!! thanks a lot!

**Comment by pdbogen** [comment]
Incidentally, on Linux, I observed this proximate problem (that the plugin didn't work after an upgrade); but I found that it was because there was a residual Mono process running that was holding open port 45531.

**Comment by theob88** [comment]
I can confirm the following worked to fix my installation on a Windows 10 machine. Quoted from the following thread: https://github.com/pfn/keepasshttp/issues/275

"I had the exact same problem with Windows 10 x64. I did some research with the exception message and found another thread that had a problem with "SetFileCompletionNotificationModes". In this case the culprit was a buggy uninstalling of a Lavasoft software _(Ad-Aware)_ which left the LavasoftTcpService64.dll in the System32 directory."

"Simply reset the Winsock Catalog from the command prompt as an admin:

netsh winsock reset

Then, restart your PC and delete the buggy files from:

C:\WINDOWS\system32\LavasoftTcpService64.dll
C:\WINDOWS\SysWOW64\LavasoftTcpService.dll"

I've read elsewhere that some people only had to do the winsock reset but I deleted the lavasoft files anyway since I don't have Ad Aware installed anymore.  Hope this helps!
