### ISSUE TITLE
first run on Keepass 2.20.1 or later, throws HttpApi exception

### ISSUE THREAD

**Issue by larsberntrop** [pfn/keepasshttp#83]
Running Keepass 2.20.1 or later on Windows7-x64
copying https://passifox.appspot.com/KeePassHttp.plgx too Keepass dir and restarting produces (<username> and <cacheKey> redacted):

[Content]: The following plugin is incompatible with the current KeePass version:
C:\Users\username\AppData\Local\KeePass\PluginCache\cacheKey\KeePassHttp.dll
note: username and cachekey are placeholders for the actual value

Have a look at the plugin's website for an appropriate version.

[Expanded Information]
The type initializer for 'HttpApi' threw an exception.
System
   at System.Net.UnsafeNclNativeMethods.HttpApi.get_Supported()
   at KeePassHttp.KeePassHttpExt.Initialize(IPluginHost host)
   at KeePass.Plugins.PluginManager.LoadPlugins(FileInfo[] vFiles, String strTypeName, String strDisplayFilePath, Boolean bSkipCacheFiles)
Boolean get_Supported()

Inner:
The type initializer for 'System.Net.ComNetOS' threw an exception.
System
   at System.Net.UnsafeNclNativeMethods.HttpApi..cctor()
Void .cctor()
[^] Details  [OK]

**Comment by mblais** [comment]
I am having this same issue on a "freshened" WIndows 8.1 x64 installation.
KeePass2 v2.30
I tried installing Mono.
I tried updating .NET framework.
No dice.
I did not have this problem before I had to "refresh" my Windows installation.

![image](https://cloud.githubusercontent.com/assets/281745/9806250/3c6604d2-57f7-11e5-8b26-b5666aae770b.png)
